#!/bin/bash
# Post-Terraform setup: Configure kubectl, install Dapr and nginx-ingress
# Run this after 'terraform apply' completes

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/../terraform"

echo "========================================="
echo "Phase 6: Post-Terraform Cluster Setup"
echo "========================================="
echo ""

# Check prerequisites
echo "Checking prerequisites..."

if ! command -v kubectl &> /dev/null; then
    echo "ERROR: kubectl not found."
    exit 1
fi
echo "  kubectl: OK"

if ! command -v helm &> /dev/null; then
    echo "ERROR: Helm not found."
    exit 1
fi
echo "  Helm: OK"

if ! command -v dapr &> /dev/null; then
    echo "ERROR: Dapr CLI not found."
    exit 1
fi
echo "  Dapr CLI: OK"

# Load existing config or read from Terraform
CONFIG_FILE="$SCRIPT_DIR/../.azure-config"
if [ -f "$CONFIG_FILE" ]; then
    echo "  Loading existing configuration..."
    source "$CONFIG_FILE"
else
    if ! command -v terraform &> /dev/null; then
        echo "ERROR: Terraform not found and no existing config."
        echo "  Install: https://developer.hashicorp.com/terraform/install"
        exit 1
    fi
    echo "  Terraform: OK"
    echo ""

    # Get Terraform outputs
    echo "Reading Terraform outputs..."
    cd "$TERRAFORM_DIR"

    if [ ! -f "terraform.tfstate" ]; then
        echo "ERROR: Terraform state not found. Run 'terraform apply' first."
        exit 1
    fi

    RESOURCE_GROUP=$(terraform output -raw resource_group_name)
    AKS_NAME=$(terraform output -raw aks_cluster_name)
    LOCATION=$(terraform output -raw location)
fi

echo "  Resource Group: $RESOURCE_GROUP"
echo "  AKS Cluster:    $AKS_NAME"
echo ""

# Configure kubectl
echo "Configuring kubectl for AKS..."
az aks get-credentials --resource-group "$RESOURCE_GROUP" --name "$AKS_NAME" --overwrite-existing
echo "  kubectl configured"
echo ""

# Verify cluster connection
echo "Verifying cluster connection..."
kubectl get nodes
echo ""

# Install Dapr on AKS
echo "Installing Dapr on AKS..."
if kubectl get namespace dapr-system &> /dev/null; then
    echo "  Dapr already installed"
    dapr status -k
else
    dapr init -k --wait --timeout 600
    echo ""
    echo "Dapr installation complete:"
    dapr status -k
fi

# Create namespace
echo ""
echo "Creating dapr-demo namespace..."
kubectl create namespace dapr-demo 2>/dev/null || echo "  Namespace already exists"

# Create tracing config (required by ingress controller's Dapr sidecar)
echo "Creating Dapr tracing configuration..."
cat <<EOF | kubectl apply -f -
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: dapr-demo
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.dapr-demo.svc.cluster.local:9411/api/v2/spans"
EOF

# Use existing DNS label or generate new one
if [ -z "$DNS_LABEL" ]; then
    DNS_LABEL="dapr-demo-$(head /dev/urandom | tr -dc a-z0-9 | head -c 8)"
fi

# Install nginx-ingress with Dapr sidecar
echo ""
echo "Installing nginx-ingress with Dapr sidecar..."
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx 2>/dev/null || true
helm repo update ingress-nginx

helm upgrade --install api-gateway ingress-nginx/ingress-nginx \
    --namespace dapr-demo \
    --values "$SCRIPT_DIR/../config/ingress-values.yaml" \
    --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="$DNS_LABEL" \
    --timeout 10m

# Wait for the ingress controller
echo "  Waiting for ingress controller..."
kubectl wait --for=condition=available --timeout=300s deployment/api-gateway-ingress-nginx-controller -n dapr-demo

# Get public IP
echo ""
echo "Waiting for public IP assignment..."
EXTERNAL_IP=""
while [ -z "$EXTERNAL_IP" ]; do
    EXTERNAL_IP=$(kubectl get svc api-gateway-ingress-nginx-controller -n dapr-demo -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)
    if [ -z "$EXTERNAL_IP" ]; then
        echo "  Waiting for external IP..."
        sleep 10
    fi
done

# Save configuration for other scripts
CONFIG_FILE="$SCRIPT_DIR/../.azure-config"
cat > "$CONFIG_FILE" << EOF
# Azure configuration - generated by setup-cluster.sh
# Source this file in other scripts: source \$SCRIPT_DIR/../.azure-config
RESOURCE_GROUP="$RESOURCE_GROUP"
LOCATION="$LOCATION"
AKS_NAME="$AKS_NAME"
DNS_LABEL="$DNS_LABEL"
EXTERNAL_IP="$EXTERNAL_IP"
EOF

echo ""
echo "========================================="
echo "Cluster Setup Complete!"
echo "========================================="
echo ""
echo "Resources:"
echo "  Resource Group: $RESOURCE_GROUP"
echo "  AKS Cluster:    $AKS_NAME"
echo ""
echo "Public access:"
echo "  IP Address: $EXTERNAL_IP"
echo "  URL: http://$DNS_LABEL.$LOCATION.cloudapp.azure.com"
echo ""
echo "Next steps:"
echo "  1. ./scripts/build-and-push.sh --with-frontend"
echo "  2. ./scripts/deploy-all.sh --with-frontend"
echo ""
echo "Configuration saved to: $CONFIG_FILE"
echo "========================================="
